[package]
name = "pxp-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
schemars = { version = "0.8.11" }
serde = { version = "1.0.149", features = ["derive"] }
serde_json = { version = "1.0.89" }