[package]
name = "pxp-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
pxp-span = { path = "../pxp-span" }
pxp-bytestring = { path = "../pxp-bytestring" }
pxp-token = { path = "../pxp-token" }