[package]
name = "pxp-token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pxp-span = { path = "../pxp-span" }
pxp-bytestring = { path = "../pxp-bytestring" }